id: IBF90C979
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T07:23:13+00:00'
last_modified: '2022-06-07T12:02:00.770910+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS45961
  title: ཉག་བླ་རང་རིག་རྡོ་རྗེའི་རྣམ་ཐར་དང་མགུར་འབུམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    574C:
      image_group_id: I1GS45964
      title: Volume 1 of nyag bla rang rig rdo rje'i rnam thar dang mgur 'bum
      total_pages: 374
      order: 1
      base_file: 574C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
